version: '3'

services:
  app:
    image: some-image
    build: 
      context: .
      dockerfile: Dockerfile
  proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app