name: "build-test"
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pr-autobuild action for building PR
        run: "yarn build"
      
